# Generated by Django 3.1.8 on 2021-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userDescription', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
