# Generated by Django 3.1.8 on 2021-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='', max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Permission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDUser', models.CharField(max_length=100)),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('LinkContest', models.CharField(max_length=100)),
                ('LinkDataTrain', models.CharField(max_length=100)),
                ('LinkDataTest', models.CharField(max_length=100)),
                ('LinkTester', models.CharField(max_length=100)),
                ('TimeRegister', models.DateTimeField()),
                ('TimeStart', models.DateTimeField()),
                ('TimeEnd', models.DateTimeField()),
                ('TimeOut', models.IntegerField()),
                ('IDLanguage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDContest', models.CharField(max_length=100)),
                ('IDUser', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDcontest', models.CharField(max_length=100)),
                ('IDUser', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('TimeSubmit', models.DateTimeField()),
                ('LinkSubmit', models.CharField(max_length=100)),
            ],
        ),
    ]
