# Generated by Django 2.2.24 on 2021-10-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='IDLanguage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
